---
  galaxy_info:
    author: Chungpt
    description: 
    company: Vccloud
    min_ansible_version: 1.2
    platforms:
      - name: Ubuntu
        versions:
          - all
      - name: EL
        versions:
          - all
    categories:
      - database: sql 
  dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
